services:
  fides:
    image: ethyca/fides:local
    command: uvicorn --host 0.0.0.0 --port 8080 --reload fidesctl.api.main:app
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://0.0.0.0:8080/api/v1/health"
        ]
      interval: 15s
      timeout: 5s
      retries: 5
    ports:
      - "8080:8080"
    depends_on:
      fides-db:
        condition: service_healthy
    expose:
      - 8080
    environment:
      FIDES__CONFIG_PATH: "/fides/.fides/"
      FIDESCTL__CLI__ANALYTICS_ID: ${FIDESCTL__CLI__ANALYTICS_ID}
      FIDESCTL__CLI__SERVER_HOST: "fides"
      FIDESCTL__CLI__SERVER_PORT: "8080"
      FIDESCTL__DATABASE__SERVER: "fides-db"
      FIDESCTL_TEST_MODE: "True"
    volumes:
      - type: bind
        source: .
        target: /fides
        read_only: False

  fidesops:
    image: ethyca/fides:local
    command: python -c "from fidesctl.api.ops_main import start_webserver; start_webserver()"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080/health" ]
      interval: 15s
      timeout: 5s
      retries: 5
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - fides-db
    expose:
      - 8080
    environment:
      - FIDESOPS__DEV_MODE=True
      - FIDESOPS__LOG_PII=${FIDESOPS__LOG_PII}
      - FIDESOPS__HOT_RELOAD=${FIDESOPS__HOT_RELOAD}
      - FIDESOPS__ROOT_USER__ANALYTICS_ID="internal"
      - FIDESOPS__EXECUTION__WORKER_ENABLED=True
    volumes:
      - type: bind
        source: .
        target: /fides
        read_only: False

  fides-ui:
    image: ethyca/fides:local-ui
    command: npm run dev-docker
    depends_on:
      - fides
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /fides
        read_only: False
    environment:
      - NEXT_PUBLIC_FIDESCTL_API_SERVER=http://fides:8080

  fides-db:
    image: postgres:12
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "fides"
      POSTGRES_DB: "fides"
    deploy:
      placement:
        constraints:
          - node.labels.fides.app-db-data == true

  docs:
    build:
      context: docs/fides/
    volumes:
      - ./docs/fides:/docs
      - ./:/fides
    environment:
      - FIDESOPS__DEV_MODE=True
      - FIDESOPS__LOG_PII=${FIDESOPS__LOG_PII}
      - FIDESOPS__HOT_RELOAD=${FIDESOPS__HOT_RELOAD}
      - FIDESOPS__ROOT_USER__ANALYTICS_ID=${FIDESOPS__ROOT_USER__ANALYTICS_ID}
      - FIDESOPS__EXECUTION__WORKER_ENABLED=True

  redis:
    image: "redis:6.2.5-alpine"
    command: redis-server --requirepass testpassword
    environment:
      - REDIS_PASSWORD=testpassword
    expose:
      - 6379
    ports:
      - "0.0.0.0:6379:6379"

  worker:
    image: ethyca/fides:local
    command: fides worker
    depends_on:
      redis:
        condition: service_started
    restart: always
    volumes:
      - type: bind
        source: ./
        target: /fides
        read_only: False
      - /fides/src/fides.egg-info

volumes:
  postgres: null
